version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  secrets_scan:
    executor: node/default
    steps:
      - checkout
      - run:
          name: git-secrets scan
          command: |
            pushd /var/tmp
            git clone https://github.com/awslabs/git-secrets.git
            cd git-secrets
            sudo make install
            popd
            git secrets --register-aws --global
            git secrets --scan

  # https://github.com/facebook/create-react-app/issues/6109
  npm_audit:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: pnpm i
      - save_cache:
          paths:
            - node_modules
            - client/node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: audit
          command: |
            pnpm audit

  deploy_frontend:
    executor: node/default
    parameters:
      environment:
        type: string
    environment:
      ENVIRONMENT: << parameters.environment >>
      VITE_REGION: ${REGION}
      VITE_BUCKET: ${BUCKET}
      VITE_URL: ${URL}
      VITE_USER_POOL_ID: ${USER_POOL_ID}
      VITE_APP_CLIENT_ID: ${APP_CLIENT_ID}
      VITE_IDENTITY_POOL_ID: ${IDENTITY_POOL_ID}
    steps:
      - checkout
      - run:
          name: deploy UI
          command: |
            cd client
            sudo apt -y update
            sudo apt install -y python3-pip
            pip3 --version
            sudo pip3 install --upgrade awscli
            aws --version
            cat src/config.js
            pnpm i
            pnpm run deploy

  # sls_deploy:
  #   executor: node-executor
  #   steps:
  #     - checkout
  #     - run:
  #        name: deploy serverless api
  #        command: |
  #          cd api
  #          sudo npm i -g serverless
  #          npm ci
  #          sls deploy

workflows:
  deploy:
    jobs:
      - secrets_scan:
          name: secrets_scan
      - npm_audit:
          name: npm_audit
          requires:
            - secrets_scan
      - deploy_frontend:
          name: deploy_frontend
          environment: dev
          requires:
            - npm_audit
      # - sls_deploy:
      #     name: severless deploy
      #     requires:
      #       - npm_deploy
