version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:8.15

jobs:
  secrets_scan:
    executor: node-executor
    steps:
      - checkout
      - run:
         name: git-secrets scan
         command: |
           pushd /var/tmp
           git clone https://github.com/awslabs/git-secrets.git
           cd git-secrets
           sudo make install
           popd
           git secrets --register-aws --global
           git secrets --scan

  # https://github.com/facebook/create-react-app/issues/6109
  npm_audit:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "my-page-app-client/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cd my-page-app-client && npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "my-page-app-client/package-lock.json" }}
      - run:
          name: audit
          command: |
            cd my-page-app-client
            echo npm audit

  npm_deploy:
    executor: node-executor
    parameters:
      environment:
        type: string
    environment:
      ENVIRONMENT: << parameters.environment >>
    steps:
      - checkout
      - run:
         name: deploy UI
         command: |
           cd my-page-app-client
           sudo apt -y update
           sudo apt install -y python-pip
           sudo pip install --upgrade awscli
           aws --version
           cat src/config.js
           npm ci
           npm run deploy
           echo "open http://my-page-app-v2-final-deploy.s3-website-ap-southeast-2.amazonaws.com/"

workflows:
  test:
    jobs:
      - secrets_scan:
          name: secrets_scan
      - npm_audit:
          name: npm_audit
          requires:
            - secrets_scan
      - npm_deploy:
          name: npm_deploy_dev
          environment: dev
          requires:
            - dev_approval
